name: BlastFishing
main: com.jstnf.blastfishing.BlastFishingPlugin
version: 2.0.0
author: pokeball92870 / jstnf
description: Simple and customizable blast fishing with TNT in Minecraft.
commands:
  blastfishing:
    description: Command for the BlastFishing plugin.
    usage: /blastfishing
    aliases: bf
    permission: blastfishing.blastfishing
    permission-message: You do not have permission to use this command.
permissions:
  blastfishing.*:
    description: Gives access to all BlastFishing commands and perks.
    children:
      blastfishing.admin: true
      blastfishing.reload: true
      
  blastfishing.toggle.*:
    description: Allows the toggling of all BlastFishing options.
    children:
      blastfishing.toggle.blastfishing: true
      blastfishing.toggle.playercheck: true
      blastfishing.toggle.permissioncheck: true
      
  blastfishing.loottable.*:
    description: Allows the user to test and modify the BlastFishing loot table.
    children:
      blastfishing.loottable.items: true
      blastfishing.loottable.list: true
      blastfishing.loottable.get: true
      blastfishing.loottable.add: true
      blastfishing.loottable.remove: true
      blastfishing.loottable.random: true
      
  blastfishing.admin:
    description: All admin permissions over BlastFishing.
    children:
      blastfishing.toggle.*: true
      blastfishing.loottable.*: true
      blastfishing.use: true
      blastfishing.help: true
      blastfishing.blastfishing: true
      blastfishing.menu: true
      
  blastfishing.blastfishing:
    description: Allows the use of the /blastfishing command.
    default: true
    
  blastfishing.use:
    description: Allows the user to blast fish if permission check is enabled.
    default: false
    
  blastfishing.help:
    description: Allows the user to see command help for BlastFishing.
    default: false
    
  blastfishing.menu:
    description: Allows the user to use the BlastFishing GUI.
    default: false
    
  blastfishing.reload:
    description: Allows the user to reload the BlastFishing configuration.
    default: false
    
  blastfishing.toggle.blastfishing:
    description: Allows the user to toggle BlastFishing for the entire server.
    default: false
    
  blastfishing.toggle.playercheck:
    description: Allows the user to toggle the player check for BlastFishing.
    default: false
    
  blastfishing.toggle.permissioncheck:
    description: Allows the user to toggle the permission check for BlastFishing.
    default: false
    
  blastfishing.loottable.items:
    description: Allows the user to open a GUI that lists items in the loot table.
    default: false
    
  blastfishing.loottable.list:
    description: Allows the user to list the loot table items in chat.
    default: false
    
  blastfishing.loottable.get:
    description: Allows the user to spawn in items from the loot table.
    default: false
    
  blastfishing.loottable.add:
    description: Allows the user to add their held item to the loot table.
    default: false
    
  blastfishing.loottable.remove:
    description: Allows the user to remove items from the loot table.
    default: false
    
  blastfishing.loottable.random:
    description: Allows the user to randomly spawn in an item from the loot table (uses item weight).
    default: false